### ISSUE TITLE
error when combine lora weight

### ISSUE THREAD

**Issue by chris111110** [iwalton3/mpt-lora-patch#1]
python export_hf_checkpoint.py /home/LMFlow/cn_llama/packages/new/llm-foundry/mpt-7b-instruct /home/LMFlow/cn_llama/packages/alpaca-lora-main/zl_lora ./
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
/root/.cache/huggingface/modules/transformers_modules/mpt-7b-instruct/attention.py:148: UserWarning: Using `attn_impl: torch`. If your model does not use `alibi` or `prefix_lm` we recommend using `attn_impl: flash` otherwise we recommend using `attn_impl: triton`.
  warnings.warn('Using `attn_impl: torch`. If your model does not use `alibi` or ' + '`prefix_lm` we recommend using `attn_impl: flash` otherwise ' + 'we recommend using `attn_impl: triton`.')
Loading checkpoint shards: 100%|████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.07s/it]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/LMFlow/cn_llama/packages/new/mpt-lora-patch-master/export_hf_checkpoint.py:25  │
│ in <module>                                                                                      │
│                                                                                                  │
│   22 │   trust_remote_code=True,                                                                 │
│   23 )                                                                                           │
│   24                                                                                             │
│ ❱ 25 lora_model = PeftModel.from_pretrained(                                                     │
│   26 │   base_model,                                                                             │
│   27 │   lora_path,                                                                              │
│   28 │   device_map={"": "cpu"},                                                                 │
│                                                                                                  │
│ /home/LMFlow/cn_llama/packages/new/llm-foundry/llmfoundry-venv/lib/python3.9/site-pa │
│ ckages/peft/peft_model.py:180 in from_pretrained                                                 │
│                                                                                                  │
│    177 │   │   if config.task_type not in MODEL_TYPE_TO_PEFT_MODEL_MAPPING.keys():               │
│    178 │   │   │   model = cls(model, config, adapter_name)                                      │
│    179 │   │   else:                                                                             │
│ ❱  180 │   │   │   model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, ad  │
│    181 │   │   model.load_adapter(model_id, adapter_name, **kwargs)                              │
│    182 │   │   return model                                                                      │
│    183                                                                                           │
│                                                                                                  │
│ /home/LMFlow/cn_llama/packages/new/llm-foundry/llmfoundry-venv/lib/python3.9/site-pa │
│ ckages/peft/peft_model.py:662 in __init__                                                        │
│                                                                                                  │
│    659 │   """                                                                                   │
│    660 │                                                                                         │
│    661 │   def __init__(self, model, peft_config: PeftConfig, adapter_name="default"):           │
│ ❱  662 │   │   super().__init__(model, peft_config, adapter_name)                                │
│    663 │   │   self.base_model_prepare_inputs_for_generation = self.base_model.prepare_inputs_f  │
│    664 │                                                                                         │
│    665 │   def forward(                                                                          │
│                                                                                                  │
│ /home/LMFlow/cn_llama/packages/new/llm-foundry/llmfoundry-venv/lib/python3.9/site-pa │
│ ckages/peft/peft_model.py:99 in __init__                                                         │
│                                                                                                  │
│     96 │   │   self.base_model_torch_dtype = getattr(model, "dtype", None)                       │
│     97 │   │   if not isinstance(peft_config, PromptLearningConfig):                             │
│     98 │   │   │   self.peft_config[adapter_name] = peft_config                                  │
│ ❱   99 │   │   │   self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](          │
│    100 │   │   │   │   self.base_model, self.peft_config, adapter_name                           │
│    101 │   │   │   )                                                                             │
│    102 │   │   │   self.set_additional_trainable_modules(peft_config, adapter_name)              │
│                                                                                                  │
│ /home/LMFlow/cn_llama/packages/new/llm-foundry/llmfoundry-venv/lib/python3.9/site-pa │
│ ckages/peft/tuners/lora.py:154 in __init__                                                       │
│                                                                                                  │
│   151 │   │   self.model = model                                                                 │
│   152 │   │   self.forward = self.model.forward                                                  │
│   153 │   │   self.peft_config = config                                                          │
│ ❱ 154 │   │   self.add_adapter(adapter_name, self.peft_config[adapter_name])                     │
│   155 │                                                                                          │
│   156 │   def add_adapter(self, adapter_name, config=None):                                      │
│   157 │   │   if config is not None:                                                             │
│                                                                                                  │
│ /home/LMFlow/cn_llama/packages/new/llm-foundry/llmfoundry-venv/lib/python3.9/site-pa │
│ ckages/peft/tuners/lora.py:161 in add_adapter                                                    │
│                                                                                                  │
│   158 │   │   │   model_config = self.model.config.to_dict() if hasattr(self.model.config, "to   │
│   159 │   │   │   config = self._prepare_lora_config(config, model_config)                       │
│   160 │   │   │   self.peft_config[adapter_name] = config                                        │
│ ❱ 161 │   │   self._find_and_replace(adapter_name)                                               │
│   162 │   │   if len(self.peft_config) > 1 and self.peft_config[adapter_name].bias != "none":    │
│   163 │   │   │   raise ValueError(                                                              │
│   164 │   │   │   │   "LoraModel supports only 1 adapter with bias. When using multiple adapte   │
│                                                                                                  │
│ /home/LMFlow/cn_llama/packages/new/llm-foundry/llmfoundry-venv/lib/python3.9/site-pa │
│ ckages/peft/tuners/lora.py:254 in _find_and_replace                                              │
│                                                                                                  │
│   251 │   │   │   │   │                                                                          │
│   252 │   │   │   │   │   self._replace_module(parent, target_name, new_module, target)          │
│   253 │   │   if not is_target_modules_in_base_model:                                            │
│ ❱ 254 │   │   │   raise ValueError(                                                              │
│   255 │   │   │   │   f"Target modules {lora_config.target_modules} not found in the base mode   │
│   256 │   │   │   │   f"Please check the target modules and try again."                          │
│   257 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Target modules ['q_proj', 'v_proj'] not found in the base model. Please check the target modules 
and try again.

**Comment by iwalton3** [comment]
Looks like you are trying to merge a LoRA for llama into MPT 7B. They aren't compatible. You can only merge a LoRA made for MPT 7B into MPT 7B.

**Comment by chris111110** [comment]
Could you provide code for fine-tuning MPT by LORA? thank you

**Comment by iwalton3** [comment]
That's what this repository is for. You use it with text-generation-webui.

**Comment by ChrisXULC** [comment]
hi, when I try to training, a error I met 
in/modules/training.py", line 313, in do_train
    prepare_model_for_int8_training(shared.model)
  File "/root/anaconda3/envs/webui/lib/python3.10/site-packages/peft/utils/other.py", line 70, in prepare_model_for_int8_training
    model.gradient_checkpointing_enable()
  File "/root/anaconda3/envs/webui/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1612, in gradient_checkpointing_enable
    raise ValueError(f"{self.__class__.__name__} does not support gradient checkpointing.")
ValueError: MPTForCausalLM does not support gradient checkpointing.

**Comment by chris111110** [comment]
When training the model, I encountered an issue that the loss value of the model is always 0. What could be the possible reasons for it? Thank you very much for your help!

**Comment by iwalton3** [comment]
You need to copy the files from this repo into the MPT 7B model folder.

**Comment by aggarwalanuj31** [comment]
> You need to copy the files from this repo into the MPT 7B model folder.

Will this work for [replit-code-v1-3b] as it is an MPT model?
